//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class BlockInfo
{
	public BlockInfo ()
	{
	}
	public int X;
	public int Y;
	public int Z;
	public Chunk Chunk;
	public byte Block;
}
